---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subdir
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agate/argocd-sync-wave.git
    targetRevision: HEAD
    path: subdir/versions/2
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd-sync-wave
    server: https://kubernetes.default.svc
