---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: onedir-sync-wave-0 # default
  namespace: argocd-sync-wave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onedir-nginx
  template:
    metadata:
      labels:
        app: onedir-nginx
        version: "2"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: app
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
