---
apiVersion: batch/v1
kind: Job
metadata:
  name: subdir-post-sync-wave-0
  namespace: argocd-sync-wave
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: runner
        image: busybox
        command:
        - /bin/sh
        - -c
        - echo sleep 15 seconds && sleep 15 && echo done wave 0
  backoffLimit: 3
